language: node_js
node_js:
  - "10"
before_install:
  - npm install -g parcel-bundler
  - chmod +x build.sh
  - git checkout -B gh-pages
  - git push origin gh-pages
  - git checkout master
after_success:
  - ./build.sh
script:
  - parcel build --public-url ./actenda/ index.html
