language: node_js
node_js:
  - "10"
before_install:
  - npm install -g parcel-bundler
  - git checkout master
  - chmod +x build.sh
after_success:
  - ./build.sh
script:
  - parcel build --public-url /actenda/ index.html
